### PR TITLE
Add Yolk to Flux Challenge :neckbeard:

### PR DESCRIPTION
**Pull request by garbles**

### CODE REVIEW

**Comment by staltz** [comment]
Cool! :sunglasses: 

However, very funky looking scroll buttons:

screen shot 2015-11-11 at 19 08 23

Can you fix them?

**Comment by garbles** [comment]
Oh whaaaat? I am definitely not seeing that.

screen shot 2015-11-11 at 11 21 31 am

**Comment by garbles** [comment]
Tried to reproduce without any luck :disappointed:

**Comment by staltz** [comment]
I just re-pulled this PR and still same issue. Maybe it's the bundled JS? I didn't use watchify or any build task.

**Comment by staltz** [comment]
Ok, most likely it has nothing to do with your submission. This is happening in other submissions as well. I'm suspecting it was a flexbox bug in Chrome Canary (which I'm using). Anyway, I'll merge your PR. Thanks!

**Comment by garbles** [comment]
:tada:

**Pull request merged**
