### PR TITLE
My implementation

### PR DESCRIPTION
**Pull request by winstonewert**
Here is my implementation, it uses redux and a diff-based request strategy.

### CODE REVIEW

**Comment by staltz** [comment]
On `npm start` I got:

```
module.js:338
    throw err;
    ^

Error: Cannot find module 'es6-promise'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/staltz/flux-challenge/submissions/winstonewert/webpack.config.js:3:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

For this purpose it would be good to generate the bundled js and have no required build steps to run a submission. Otherwise looks good.

**Comment by staltz** [comment]
I'll merge your submission after it has a bundled js. Thanks!

**Comment by SamLebarbare** [comment]
@winstonewert Very Elegant! perfect usage of redux :) :candy:

**Comment by winstonewert** [comment]
@SamLebarbare, thanks!

@staltz, npm start should work now, but I've also added the bundle.js.

**Comment by staltz** [comment]
Yep, all requirements passed. You're the first one.

**Pull request merged**
