### PR TITLE
Solution using Derivables

### PR DESCRIPTION
**Pull request by ds300**
See [DerivableJS](https://github.com/ds300/derivablejs). The dom rendering library ([ddom](https://github.com/ds300/ddom)) is still totally raw and not user-friendly (this is the first thing I've used it for), but its core idea definitely works which is nice.

### CODE REVIEW

**Comment by ds300** [comment]
Please don't merge this yet. I'm still figuring out how to use these tools and I now think the code here could be cleaned up a lot. I'll let you know when it's ready. :smile:

**Comment by ds300** [comment]
I'm fairly happy with this now, please feel free to merge.

It certainly represents my current thinking on how to structure apps when using Derivables, (aside from including event sourcing with e.g. redux, which just seemed like overkill for such a tiny app. If you understand event sourcing, you'll understand exactly where it would fit in here (hint: see mutations.ts)).

More info in the readme.

**Comment by staltz** [comment]
Hi David, thanks for the submission.

Some problems still, check this gif:

ds300

That sudden jump from `[Vader,,,,]` to `[,,,Vader,Antinnis]` shouldn't happen. Read more about it here #36.

Also, you don't need to set the inline style of each slot to `color: white;`. Just leave it unset.

**Comment by ds300** [comment]
Alright I fixed these issues :+1:

What's up with the buttons changing size in your gif? Surely that's not my doing...

**Comment by staltz** [comment]
> What's up with the buttons changing size in your gif? Surely that's not my doing...

That's a Flex bug that only happens in Chrome Canary, and I haven't figured out a solution yet. You can ignore it.

**Comment by staltz** [comment]
And... merged! Thanks!

**Comment by ds300** [comment]
Thank you for setting this up! It was good fun and most educational.

**Pull request merged**
