### PR TITLE
Adding React with no Flux solution

### PR DESCRIPTION
**Pull request by masiulis**
Wanted to try this for quite some time. I have been using flux/redux in production for more than half a year. One question has been bugging me, what if Flux is unnecessary? What if all we need is sending information down the component tree and listening for callbacks? Why have some global state and actions that can be called from everywhere? Does this abstraction cost more than it is worth?
The answer that I came up is that flux is unnecessary but really useful for separation of concerns. You can divide sending an action from what that action does. It's much easier to not have a tight coupling between components. *If anyone has a better answer, I am all ears.
Is it possible to build a scalable solution without flux/redux? Yes, but not with the tools that we have right now. You would probably have to build a visual component editor because connections between components get quite complex really fast (flux does not remove complexity, just divides it into actions/stores, here everything is inside a component).
Did I feel more productive? At first, yes, because everything is happening inside a component. I didn't have to think what should live as an action and what should be in stores. At the end it became really hard to maintain the main component because I couldn't find a logical way to divide it.
Does it make easier for others to understand this? No idea, probably not.

### CODE REVIEW

**Comment by staltz** [comment]
This works, thanks.

**Comment by staltz** [comment]
Good conversation starter, actually. In a way you are deliberately submitting a non-elegant solution ("_Does it make easier for others to understand this? No idea, probably not._") to a challenge that is mainly about elegance. I think the submission of a only-components solution is interesting to compare with so-called elegant solutions and check if in fact Flux made a difference.

As you said yourself: "_The answer that I came up is that flux is unnecessary but really useful for separation of concerns._"
Usually, without separation of concerns we gain two things: less code (because you can take shortcuts), and faster productivity in the beginning only. And separation of concerns brings better productivity in the long run, but introduces a bit more boilerplate/indirection code.

About Flux itself, I like to think of it as an orchestrator of UI programs, while React components are UI programs. A misconception people have is that React components are just the View. Traditionally (unless you only write dumb/stateless components), they are a full UI programs: Model (internal state), Controller (event handler callbacks), and View (render function). Read more about this here: http://staltz.com/unidirectional-user-interface-architectures.html

According to my article, yes it would be possible to build an architecture without Flux, only with React components. Such architecture could be "fractal". The biggest challenge, like in typical JS MVC frameworks, would be writing a codebase such that you can easily track the flow of data. That's why I'm building Cycle.js where data flow is explicit, you can easily build a "minimap" data flow graph of your codebase, and I plan to build tools that automate that.

**Comment by masiulis** [comment]
There is a certain beauty in having logic encapsulated in 3 nested components. Gives me a peace of mind when I don't have maintain actions/stores that are only used once. The biggest trouble for me always was that the state is global, even a state that should belong to a single component.

It would be a problem if some part of the program wanted to reuse data (like adding a sith counter at the top is easy in every implementation except this one). I would then have to move logic into a component higher in the tree, so both parts could get the same data as props. That's why mentioned that tools are needed for this, because maintaining this should not be done by hand. 

It does not seem to suffer from the same MVC problems because of single data flow. Programming this did felt more like OOP probably because I didn't want to use rxjs.

Really good point about React being not just a view. Now I want to build a complete opposite of this with stateless components + rx.js and see how it fares. I feel like in the end I'll just start using cycle.js.

**Comment by staltz** [comment]
> I feel like in the end I'll just start using cycle.js.

However, Cycle.js apps are not usually using the global state approach! In fact, it's much more like components with local state, and passing around data to each other. Check out this https://github.com/futurice/power-ui

**Comment by davedx** [comment]
I'm currently doing this in my side project. In something of a reaction to all the complexity of my day job, where we use all the latest "React hotness" (redux, react-router, reselect, etc.), I'm attempting to build a multi-view React app using just React and the smallest, simplest libraries possible (director for routing, superagent for fetching data). I'll probably pull in eventemitter to implement (user) actions, and see how it all works together.

My theory is that the architecture will not be any more or less complex than a "flux" architecture, because "flux" at its heart is just a programmer-enforced message passing system. There's nothing magical about it, and (somewhat to its detriment in my opinion), nothing in the various implementations stops programmers from e.g. doing side effectful actions inside reducers or whatever. So what does it really buy us? Is flux, or redux, just a set of guidelines with a reference implementation at the end of the day?

Great discussion. We should constantly question everything, no matter how frustrating it is when we decide we need to redesign/reimplement something new yet again.

**Comment by staltz** [comment]
Good inputs @davedx. Flux is essentially a convention on how to use event buses to broadcast user events to a forest of components. Event buses are a global artifact. Introducing a global element to an architecture usually has some (positive and negative) effects. On one hand it simplifies the system, because everything communicates with this central hub. On the other hand, it reduces reusability, since it's easy to put all state in the global artifact instead of making encapsulated self-sufficient components.

**Comment by alexeyraspopov** [comment]
@masiulis congrats, now you have view layer mixed with domain logic.

**Comment by ghost** [comment]
Two concerns for me with using the flux libraries are reusability of components and the process of understanding how a new component work. You cannot just import and call a React component, you need to import its actions, stores (the stores may have name clash problems in big projects). Also because the functionality is broken in several files, to have a complete picture of how one component works it takes more cognitive load to follow up all actions and create a mental model for them.

What I'm trying lately is to have self-sustained components in relation to their flow of data. The main purpose of a React component is to map the props it receives to ui elements or other components. Why not put the inverse logic also inside of the same component? To make the components also responsible to map the update of the props from its child components back to a update of its own props.

For that I'm using the following pattern, all the state is hold up by the root component, all components have an 'onUpdate' prop that they call with their updated props in response to browser events or 'onUpdate' calls from their children. With that all interactions bubble up to the root and then flow down again for re-rendering the UI, logic is fully encapsulated as the components only need to know how to map their props to child elements and how to map back its child elements props back to an update of its own props.

Example:

``` jsx
import React, {PropTypes} from 'react'
import Block from '../Block'
import defaultTheme from '../defaultTheme'

export const handleAnnotationUpdate = (props, annotationProps) => {
  props.onUpdate({
    ...props,
    text: annotationProps.text,
  })
}

const ExampleComponent = props => (
  <Block>
    <Annotation
      text={props.text}
      theme={props.theme}
      onUpdate={handleAnnotationUpdate.bind(null, props)}
    />
  </Block>
)

ExampleComponent.propTypes = {
  onUpdate: PropTypes.func,
  text: PropTypes.string.isRequired,
  theme: PropTypes.object,
}
ExampleComponent.defaultProps = {
  theme: defaultTheme,
}

export default ExampleComponent
```

**Comment by troch** [comment]
I totally agree with flux (or similar) being a convention more than anything else, and beneficial on the long run rather than bringing short-term benefits. On larger projects, it improves composability by removing some or all business logic from components. It also allows quicker refactoring and therefore better incremental development. It is common these days to talk about smart vs dumb components. When making components stateless and having state outside them, you can have all your components dumb and only use higher-order components to connect to state, context and environment (browser, etc...).

**Comment by AoDev** [comment]
Hi, I don't use flux anymore in my apps (or any variant like redux, etc.). Note, I have not built a huge app this way. I found frameworks built with the Flux concept an incredibly bloated way to do just one thing: update the store.

So I removed all the actions, actions creators, constants part. I only have a store with public methods to update it. (you can obviously structure your code so that the store does not end like a huge module with tons of public methods) The store can be required in any component. Only the top react component listens to the store/state change.

There are basically two types of data: the one that needs to be shared and the one that is useful only to its component.

I put the data that needs to be shared into the store. It is then passed through the React components tree.
Regarding the data that only belongs to a component, I decided to create two kinds of component:
- the dumb view: just displays the data I pass to it. 
- the dataProvider component: will fetch the data. (does not matter how, but usually, ajax)

Vantages of this, I can do this:

```
<DataProviderOfDumbView>
  <DumbView data={data}/>
</DataProviderOfDumbView>
```

If I want to provide the data to this component (dumbView) in a different way, in a different project, I just have to copy it. Totally reusable. 

And regarding the shared state, in the store:

```
// some component
var store = require('store')

...
onButtonClicked() {
  store.changeSomething()
}
// store is updated, react root component was listening and passes the data to the children.
```

Note that most of the time we don't need to store data from requests. If your server sends proper expire times the browser does the caching for us.

**Comment by gilbox** [comment]
Just tweeted [this](https://twitter.com/gilboxme/status/661092369534615553) before stumbling across [@staltz's tweet](https://twitter.com/andrestaltz/status/660763197968932864) which lead me to this thread. Anyway, maybe this is somewhat relevant...

I've been dabbling with a react architecture that relies on composing small functional react components.  I wouldn't say it's simpler than Flux, but it's more direct. Here are some of the approaches I've adopted from around the nets:
- A component that holds all the Top-level state.
- Optional sub-component-level state `decorator` that can be moved up the component hierarchy minimal refactor of sub-components.
- React components that only effect the top-level state but don't render anything at all.
- (for better or for worse), there is no `dispatcher`.
- Using reducers to modify app state.

[This demo (a game involving snowflakes)](https://github.com/gilbox/react-three-ejecta-boilerplate/blob/master/src/Game.js#L73) utilizes most of these ideas. There is, for example, an [AnimationFrame](https://github.com/gilbox/react-three-ejecta-boilerplate/blob/master/src/animationFrame.js) component that accepts a single prop, `onTick`.

I refactored the game several times, each time moving state further up the component tree... until eventually it was all at the top. Now with all the state in the top component, I think it is the best architecture of all my previous iterations. That said, I would love to know if anyone has any suggestions for improvement ( ◠‿◠ ).

**Pull request merged**
