### PR TITLE
MEGABLOB implementation

### PR DESCRIPTION
**Pull request by milankinen**
I hope the code and `README` will explain themselves.

### CODE REVIEW

**Comment by staltz** [comment]
screen shot 2015-10-12 at 10 24 37

I was able to put the application in this invalid state, it wouldn't load data anymore.

**Comment by milankinen** [comment]
What should happen if all siths are scrolled out? Or should this be prevented somehow?

**Comment by jas-chen** [comment]
Take a look at #12

**Comment by milankinen** [comment]
Thanks! Scroll preventing implemented.

It would be awesome if that "rule" could added to the README so that others can be prepared before making any PRs.

**Comment by staltz** [comment]
It's not a rule ;)

**Comment by milankinen** [comment]
Anyhow, should be fix'd now

**Comment by staltz** [comment]
Why does it take more than a second for a previously-canceled request to get resent again? E.g. try pressing quickly down, up, down. The relevant request should be sent immediately, I don't understand why is there an idle time.

**Comment by milankinen** [comment]
My mistake... sry. It was because I was lazy and sent the cancel events every time when the scroll was pressed. :-) However, the ordering of the emitted events from `sithsScrolledS` and `appState.changes()` can't be guaranteed. 

In this case, cancel events (from `sithsScrolledS`) were emitted after the load master/apprentice events (from `appState.changes()`), resulting that no ajax request was sent after scrolling... until planet was changed (which caused new event to `appState.changes()`). 

Now sending events only from `appState.changes()` (should have done this from the very beginning...) so the order of the emitted cancels/loads is guaranteed.

**Comment by staltz** [comment]
This works. Thanks!

**Comment by aparticka** [comment]
This one's my favorite, I need to start using Bacon.

**Pull request merged**
