### PR TITLE
Mobservable based solution

### PR DESCRIPTION
**Pull request by mweststrate**
Hi André,

Finally found some time to write a Mobservable based solution :). I tried to keep it as concise as possible, so if I missed somehow something just let me know. 

I took the liberty to put the complete solution in a single file (index.tsx) to save readers the incovenience of browsing back and forth between files. Components are at the top, the application state, actions and data derivations on the bottom.

Tnx in advance,

Michel

### CODE REVIEW

**Comment by staltz** [comment]
Hi @mweststrate, thanks for the submission.

It looks almost perfect, although I managed to find some glitches here and there.

I am sure I was able to scroll while a red match was on the screen (and I am not supposed to be able to scroll at those moments). Most of the times the restriction was working, and I could not scroll during a red match. It's just sometimes that I was able to do that.

Then, the restriction for "only scroll if it wouldn't move the items out of the list" mostly worked, but sometimes didn't, and I was able to scroll twice quickly, and I got to UI to this invalid state where it wouldn't load anything anymore:

screen shot 2015-12-09 at 22 36 13

It's a challenge after all...

**Comment by staltz** [comment]
And... sorry for such long delay in answering. I was really busy since then.

**Comment by mweststrate** [comment]
No problem! I should just click the buttons more aggressively the next time
:) I'll look into it.

**Comment by mweststrate** [comment]
Hi @staltz 

My turn for a delay in answering :). Fixed the issue, Siths where loaded twice and scrolling was one off. Should be ok now.

**Comment by staltz** [comment]
Hi, thanks again for updating.

Another problem: after a red match happens and everything returns to normal, 5 requests are sent to the server, to get the siths that are _already_ on the list. Since Obi-Wan doesn't want to overload this server in vain, we should only make requests for those siths that are missing.

**Comment by mweststrate** [comment]
Ah good point! Fixed it (Next time when doing a challenge I should write automated tests first..)

**Comment by staltz** [comment]
Merged! Thanks for the submission. You can also update https://github.com/staltz/flux-challenge/blob/master/submissions/README.md if you feel like.

**Pull request merged**
