### PR TITLE
josepot submission (Redux with React) 

### PR DESCRIPTION
**Pull request by josepot**

### CODE REVIEW

**Comment by staltz** [comment]
> Your solution should be executable by opening submissions/username/index.html in the browser with no build steps.

**Comment by josepot** [comment]
@ staltz sorry about that! I got rid of the build steps and all the other unnecessary stuff. I've also done a rebase and I've squashed all my commits. Please have a look at it again, thanks!

**Comment by staltz** [comment]
Hi, thanks, but still some problems. Doesn't resume to load siths after a red match has occurred. I got stuck here, no more pending requests ever happened:

screen shot 2015-10-12 at 22 10 30

**Comment by josepot** [comment]
@staltz fixed, sorry about that! 

I actually thought that was the expected behaviour. I guess that I should have checked how the other submissions were behaving. However, the requirements don't explicitly say that this is the expected behaviour, they do mention that the UI needs to unfreeze but they don't say anything about resuming requests, although I guess that's quite obvious.

I hope that this time everything works as expected, thanks!

**Comment by staltz** [comment]
Working :+1:

**Pull request merged**
