### PR TITLE
'flux challenge' code

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by staltz** [comment]
> Your solution should be executable by opening submissions/username/index.html in the browser with no build steps.

**Comment by ghost** [comment]
Fixed. It didn't work in Chrome because it doesn't allow to load local files due to permissions. Now fixed, I moved all js code in index.html file.

**Comment by staltz** [comment]
I was able to put the app in an invalid state:

screen shot 2015-10-15 at 21 23 39

It should load the sith above Naga Sadow but it didn't. Just stayed there. Until I scroll again, of course.

**Comment by ghost** [comment]
Fixed, my fault, sorry.

**Comment by staltz** [comment]
Seems fixed, thanks!

**Pull request merged**
