### PR TITLE
Fluxlet based implementation

### PR DESCRIPTION
**Pull request by jollytoad**
Hi, this implementation uses a new micro-framework called fluxlet that we've recently been working on.
I'm hoping to write a fluxlet tutorial based on this at some point.

### CODE REVIEW

**Comment by staltz** [comment]
Hi, two problems:
- When a red match happens, existing pending requests should be cancelled.
- The submission folder should be named after your username.

**Comment by jollytoad** [comment]
I've renamed the folder.

All outstanding requests are cancelled on a match, I'm seeing the cancelled request in the network panel, also evidence of this can be seen in the logging in the console of "abortAllRequests"

https://github.com/staltz/flux-challenge/pull/28/files#diff-8c88fa3dc6d0487a4f3cc7516be22419R352

That log message will only appear if the 'when' clause evaluates to true, meaning that the 'then' function has been called.

**Comment by staltz** [comment]
> All outstanding requests are cancelled on a match, I'm seeing the cancelled request in the network panel, also evidence of this can be seen in the logging in the console of "abortAllRequests"

I'm very sure I saw a pending request while there was a red match **plus** an empty slot got filled when that request fulfilled.

**Comment by jollytoad** [comment]
Ah, well spotted. I couldn't see the requests initiating myself. So i've added some url testing params...

Add this to the url to delay the websocket and force an initial homeworld (after a 2s delay)...

?visitId=7&visitName=Naboo&delayVisit=2000&delayWebSocket=6000

Revealed that my requests were indeed initiating whilst the red match was present, which i've now fixed.
Thanks.

**Comment by staltz** [comment]
Working, thanks!

**Pull request merged**
