### PR TITLE
Submission with Redux

### PR DESCRIPTION
**Pull request by leoasis**
Handling the requests as a separate dispatcher subscription, making sure the outstanding requests reflect the state whenever it changes, creating the new ones and aborting the ones that are no longer there.

### CODE REVIEW

**Comment by staltz** [comment]
Hi, thanks for the submission.

Some problems I found:
- On startup, when connecting to the websocket, it immediately sends back a message, so there should be an initial planet, not `--`.
- If I click 3 times scroll up quickly, the program breaks, with this error:

```
render  @   App.js:81
ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @   ReactCompositeComponent.js:789
ReactCompositeComponentMixin._renderValidatedComponent  @   ReactCompositeComponent.js:816
wrapper @   ReactPerf.js:70
ReactCompositeComponentMixin._updateRenderedComponent   @   ReactCompositeComponent.js:746
ReactCompositeComponentMixin._performComponentUpdate    @   ReactCompositeComponent.js:726
ReactCompositeComponentMixin.updateComponent    @   ReactCompositeComponent.js:642
wrapper @   ReactPerf.js:70
ReactCompositeComponentMixin.receiveComponent   @   ReactCompositeComponent.js:506
ReactReconciler.receiveComponent    @   ReactReconciler.js:97
```

**Comment by staltz** [comment]
First requirement was actually my mistake, and I fixed it now.

**Comment by leoasis** [comment]
@staltz ahh, anyway I fixed it: checked the code an figured I needed to send a message on connect.

Fixed both comments :D

**Comment by staltz** [comment]
I ran your updated code, and before loading the first 3 siths, I had a red match, and then after the match passed, I couldn't scroll neither up nor down. Also, I should be able to scroll up in the beginning when the first in the list is Darth Sidious and it **is known** that he has a master.

**Comment by leoasis** [comment]
I think I have it now, if you want to review!

**Comment by staltz** [comment]
Yes, working!

**Comment by gaearon** [comment]
This is the most “Reduxy” solution so far yet.
(Although I'm still waiting for somebody to use Rx with Redux :-)

**Comment by quicksnap** [comment]
I'm very interested in feedback on this one! The implementation looks nice and clean.. @staltz, do you plan on providing critique on accepted submissions eventually?

**Comment by staltz** [comment]
@quicksnap see issue #9

**Pull request merged**
